select
    po_id,
    supplier_id,
    product_id,
    warehouse_id,
    order_date,
    expected_delivery_date,
    received_date,
    qty_ordered,
    qty_received,
    qty_shortfall,
    unit_cost,
    total_value,
    actual_lead_days,
    contracted_lead_time_days,
    days_late,
    is_late,
    is_short_shipped,
    status,
    case when is_late = 0 and is_short_shipped = 0 then 1 else 0 end as is_perfect_order
from {{ ref('int_supplier_operations') }}